apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitter-probe
  labels:
    app: jitter-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitter-probe
  template:
    metadata:
      labels:
        app: jitter-probe
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9092"
    spec:
      containers:
        - name: jitter-probe
          image: jitter-probe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
