apiVersion: v1
kind: Service
metadata:
  name: jitter-probe
  labels:
    app: jitter-probe
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9092"
spec:
  type: ClusterIP
  selector:
    app: jitter-probe
  ports:
    - name: metrics
      port: 9092
      targetPort: 9092
      protocol: TCP
