apiVersion: v1
kind: Service
metadata:
  name: dns-probe
  labels:
    app: dns-probe
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9091"
spec:
  type: ClusterIP
  selector:
    app: dns-probe
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
