apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-monitor
  labels:
    app: gateway-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-monitor
  template:
    metadata:
      labels:
        app: gateway-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9093"
    spec:
      containers:
        - name: gateway-monitor
          image: gateway-monitor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
