apiVersion: v1
kind: Service
metadata:
  name: gateway-monitor
  labels:
    app: gateway-monitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9093"
spec:
  type: ClusterIP
  selector:
    app: gateway-monitor
  ports:
    - name: metrics
      port: 9093
      targetPort: 9093
      protocol: TCP
