replicaCount: 1

image:
  repository: k3d-edge-registry:5000/dns-probe
  pullPolicy: Always
  tag: "local"

service:
  type: ClusterIP
  port: 9091
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"

ingress:
  enabled: false
  className: ""
  host: edge.local
  path: /
  pathType: Prefix

resources: {}

podAnnotations: {}

metrics:
  enabled: true
  port: 9091

env:
  DNS_TARGETS: "google.com,cloudflare.com"
  INTERVAL_SECONDS: "2"
