replicaCount: 1

image:
  repository: k3d-edge-registry:5000/wifi-probe
  pullPolicy: Always
  tag: "local"

service:
  type: ClusterIP
  port: 9090
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"

ingress:
  enabled: false
  className: ""
  host: edge.local
  path: /
  pathType: Prefix

resources: {}

podAnnotations: {}

metrics:
  enabled: true
  port: 9090

env:
  PING_TARGETS: "1.1.1.1,8.8.8.8"
  HTTP_TARGETS: "https://ifconfig.me/ip"
  INTERVAL_SECONDS: "2"
